/**********************************************************************************************************************
 * \file START_MCS.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "START_MCS.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------Function Prototypes-------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Function Implementations-----------------------------------------------*/
/*********************************************************************************************************************/

/* This function uses th CPU to copy the MCSx code image in its dedicated MCS-RAM portion. The MCS code image is stored
 * into the Aurix Flash memory.
 * */
static void copy_Mcs_Image(uint32 mcsCore, uint32 *image, uint32 imageSize)
{
    uint32 i;
    /* Calculate base address of the specific MCS core RAM */
    uint32 *mcsRam = (uint32 *)((uint32)GTM_MCS0_MEM + ((uint32)GTM_MCS1_MEM - (uint32)GTM_MCS0_MEM) * mcsCore);

    /* Calculate the total size of MCS RAM in words (approx 0x1000 bytes for typical Aurix, but dynamic calc is safer) */
    /* Note: Using the distance between MCS0 and MCS1 as a proxy for RAM size is common practice */
    uint32 ramSizeWords = ((uint32)GTM_MCS1_MEM - (uint32)GTM_MCS0_MEM) / 4;

    /* 1. Initialize ENTIRE MCS RAM to 0 to fix ECC checksums */
    for (i = 0; i < ramSizeWords; i++)
    {
        mcsRam[i] = 0x00000000;
    }

    /* 2. Write program code into MCS RAM (overwriting the zeros at the start) */
    for (i = 0; i < (imageSize / 4); i++)
    {
        mcsRam[i] = image[i];
    }

    /* 3. Data Sync Barrier: Ensure CPU writes complete before MCS tries to read */
    __dsync();
}

const uint32 MCS0_CH0_prog[] =
{
    0x10000000, /* MOVL  R0, 0  */
    0x20000001, /* ADDL  R0, 1  */
    0xE0000004  /* JMP   0x04   */
};

/* This function configures and starts GTM-MCS0_CH0-7
 * - calls the function "copy_Mcs_Image" to copy MCSx program image into its dedicate GTM-RAM portion
 * - enables XOREG registers
 * - starts MCSx execution
 * */
void start_Mcs0(void)
{
    /* 1. Ensure MCS is disabled before config */
    GTM_MCS0_CH0_CTRL.B.EN = 0u;

    /* 2. Program image to MCS0 RAM section and clear ECC */
    copy_Mcs_Image(0, (uint32 *)MCS0_CH0_prog, sizeof(MCS0_CH0_prog));

    /* 3. Enable XOREG register set (extended operation registers) */
    GTM_MCS0_CTRL_STAT.B.EN_XOREG = 1u;

    /* 4. Clear any previous error flags (Write 1 to Clear) */
    /* If ERR was 0xFF, this resets it so we can see new errors */
    GTM_MCS0_ERR.U = 0xFFFFFFFF;

    /* 5. Enable ONLY MCS0_CH0 */
    GTM_MCS0_CH0_CTRL.B.EN = 1u;

    /* DISABLE unused channels to prevent them from executing garbage code */
    GTM_MCS0_CH1_CTRL.B.EN = 0u;
    GTM_MCS0_CH2_CTRL.B.EN = 0u;
    GTM_MCS0_CH3_CTRL.B.EN = 0u;
    GTM_MCS0_CH4_CTRL.B.EN = 0u;
    GTM_MCS0_CH5_CTRL.B.EN = 0u;
    GTM_MCS0_CH6_CTRL.B.EN = 0u;
    GTM_MCS0_CH7_CTRL.B.EN = 0u;
}
