/**********************************************************************************************************************
 * \file START_MCS.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "START_MCS.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------Function Prototypes-------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Function Implementations-----------------------------------------------*/
/*********************************************************************************************************************/

/* This function uses th CPU to copy the MCSx code image in its dedicated MCS-RAM portion. The MCS code image is stored
 * into the Aurix Flash memory.
 * */
static void copy_Mcs_Image(uint32 mcsCore, uint32 *image, uint32 imageSize)
{
    uint32 i;
    /* Calculate base address of the specific MCS core RAM */
    uint32 *mcsRam = (uint32 *)((uint32)GTM_MCS0_MEM + ((uint32)GTM_MCS1_MEM - (uint32)GTM_MCS0_MEM) * mcsCore);

    /* Calculate the total size of MCS RAM in words (approx 0x1000 bytes for typical Aurix, but dynamic calc is safer) */
    /* Note: Using the distance between MCS0 and MCS1 as a proxy for RAM size is common practice */
    uint32 ramSizeWords = ((uint32)GTM_MCS1_MEM - (uint32)GTM_MCS0_MEM) / 4;

    /* 1. Initialize ENTIRE MCS RAM to 0 to fix ECC checksums */
    for (i = 0; i < ramSizeWords; i++)
    {
        mcsRam[i] = 0x00000000;
    }

    /* 2. Write program code into MCS RAM (overwriting the zeros at the start) */
    for (i = 0; i < (imageSize / 4); i++)
    {
        mcsRam[i] = image[i];
    }

    /* 3. Data Sync Barrier: Ensure CPU writes complete before MCS tries to read */
    __dsync();
}

#define CLK_PERIOD_TICKS   (100u)
#define CLK_DUTY_50        (CLK_PERIOD_TICKS/2u)

/* Helpers (same as before) */
#define MCS_MOVL(regA, imm24)   (0x10000000u | (((uint32)(regA) & 0xFu) << 24) | ((uint32)(imm24) & 0x00FFFFFFu))
#define MCS_AWRI(regA, regB)    (0xB0000000u | (((uint32)(regA) & 0xFu) << 24) | (((uint32)(regB) & 0xFu) << 20) | (0x5u << 16))
#define MCS_JMP(addr)           (0xE0000000u | ((uint32)(addr) & 0x0000FFFcu))

/* 15 instructions total -> last (JMP) at 14*4 = 0x38 */
#define MCS_PROG_END_ADDR   (0x38u)

#define NOP 0x00000000

const uint32 MCS0_CH0_prog[] =
{
    /* 0x00: Init Period (R2 = 20 ticks) */
    MCS_MOVL(2u, CLK_PERIOD_TICKS),

    /* 0x04: Init Duty (R3 = 10 ticks = 50%) */
    MCS_MOVL(3u, CLK_DUTY_50),

    /* --- BURST LABEL (0x08) --- */

    /* Generate 5 Pulses */
    /* Note: R3 holds the "Active" Duty Cycle here */
    MCS_AWRI(2u, 3u),   /* Pulse 1 */
    MCS_AWRI(2u, 3u),   /* Pulse 2 */
    MCS_AWRI(2u, 3u),   /* Pulse 3 */
    MCS_AWRI(2u, 3u),   /* Pulse 4 */
    MCS_AWRI(2u, 3u),   /* Pulse 5 */

    /* --- GAP GENERATION --- */

    /* 0x1C: Temporarily load R3 with 0 (0% Duty) */
    MCS_MOVL(3u, 0u),

    /* Send "0" for 5 cycles to create a gap */
    MCS_AWRI(2u, 3u),   /* Gap 1 */
    MCS_AWRI(2u, 3u),   /* Gap 2 */
    MCS_AWRI(2u, 3u),   /* Gap 3 */
    MCS_AWRI(2u, 3u),   /* Gap 4 */
    MCS_AWRI(2u, 3u),   /* Gap 5 */

    /* --- RESTORE & LOOP --- */

    /* 0x30: Reload R3 with 50% Duty for the next burst */
    MCS_MOVL(3u, CLK_DUTY_50),

    /* 0x34: Jump back to Burst Label (0x08) */
    MCS_JMP(0x08)
};


/* This function configures and starts GTM-MCS0_CH0-7
 * - calls the function "copy_Mcs_Image" to copy MCSx program image into its dedicate GTM-RAM portion
 * - enables XOREG registers
 * - starts MCSx execution
 * */
void start_Mcs0(void)
{
    /* Disable all channels first */
    GTM_MCS0_CH0_CTRL.B.EN = 0u;
    GTM_MCS0_CH1_CTRL.B.EN = 0u;
    GTM_MCS0_CH2_CTRL.B.EN = 0u;
    GTM_MCS0_CH3_CTRL.B.EN = 0u;
    GTM_MCS0_CH4_CTRL.B.EN = 0u;
    GTM_MCS0_CH5_CTRL.B.EN = 0u;
    GTM_MCS0_CH6_CTRL.B.EN = 0u;
    GTM_MCS0_CH7_CTRL.B.EN = 0u;

    /* Enable XOREG register set */
    GTM_MCS0_CTRL_STAT.B.EN_XOREG = 1u;

    /* Force best scheduling for single active channel
       SCD_MODE meaning is per TC3xx UM. Typically:
         0 = round robin
         1 = accelerated round robin
         2/3 = prioritized / selected channel
       You want the accelerated/single-channel one.
    */
    GTM_MCS0_CTRL_STAT.B.SCD_CH   = 0u;

    /* >>> Choose the accelerated / single-channel mode for your UM <<< */
    GTM_MCS0_CTRL_STAT.B.SCD_MODE = 1u;   /* <-- if your UM says 1=accelerated */
    /* If your UM says 2 or 3 is “selected channel only”, use that instead. */

    /* Clear any previous errors */
    GTM_MCS0_ERR.U = 0xFFFFFFFFu;

    /* Load program (and clear ECC) */
    copy_Mcs_Image(0, (uint32 *)MCS0_CH0_prog, sizeof(MCS0_CH0_prog));

    /* Select MCS0_WRADDR[0] via R6[4:0] */
    GTM_MCS0_CH0_R6.U  = (GTM_MCS0_CH0_R6.U & ~0x1Fu) | 0u;

    /* ACB = 0 (first demo) */
    GTM_MCS0_CH0_ACB.U = 0u;

    /* Enable only CH0 last */
    GTM_MCS0_CH0_CTRL.B.EN = 1u;
}

